### PR TITLE
basic linux compatibility

### PR DESCRIPTION
**Pull request by jacobfeder**
Tested on debian 10. The user must have "comsol" in their PATH. There seems to be a problem for some reason running standalone, so it must be run like:

`# port to use for the comsol server`
`PORT = 18304`
`# start comsol server`
`comsol_server = subprocess.Popen(['comsol', 'mphserver', '--port', str(PORT)])`
`# connect to comsol server`
`client = mph.Client(cores=1, port=PORT)`

### CODE REVIEW

**Comment by John-Hennig** [comment]
Hi Jacob, thanks a lot for your contribution. Sorry it took me a while to look into it and get back to you.

I've tested your code on Ubuntu 18.04 LTS. Unfortunately, even the client-server mode doesn't work. I get: `JVM DLL not found`.

This is probably fixable. You use `which comsol` to locate the Comsol executable. On Ubuntu at least (I don't know about Debian), it returns `/usr/local/bin/comsol`, which is a symlink to `/usr/local/comsol55/multiphysics/bin/glnxa64/comsol`. It's the path of the latter (to the `multiphysics` folder, to be exact) that is needed to locate Comsol's Java VM and Comsol-specific Java libraries. So it makes sense it doesn't work like that (on my Ubuntu setup).

Again, this part can be fixed. Just follow the symlink (somehow), get the actual path from there. It should then even work with a `Server` instance from the `mph.server` module.

Where I ran into repeated troubles, when I did tests some time ago, was starting the client. To be fair, I only ever tested the stand-alone mode. (Because that's all I ever need. I run multiple clients on every compute node I have access to at work and don't really see the benefit of client-server mode. It may save some memory overhead, as the Comsol documentation claims, but these are "headless" clients, without the GUI, so that's arguably a negligible effect. Anyway…) I could even get the stand-alone client to start up, but it would fail as soon as it was instructed to load a model into memory.

That's where I gave up back then. I may give this another shot… eventually. But, more than anything else, I really want the stand-alone mode to work.

**Comment by jacobfeder** [comment]
Hi @John-Hennig,
I agree that if we simply traverse the symlink it should fix that issue. I will implement that and send a new PR. Regarding the standalone mode, I will check again the error I was getting. For my use case, I'm not too picky about the difference between standalone mode and starting the server separately, as it can be done very easily with the code in the first comment. If you wanted many instances you would just have to start them on separate ports.

Cheers

**Comment by jacobfeder** [comment]
Ok symlink issue is fixed.

When I try standalone mode:

```
import mph
client = mph.Client(cores=1)
model = client.load('test.mph')
```

I get the following error when running the 3rd line (line 162 in client.py):

```
model = Model(self.java.load(tag, str(file)))
java.lang.UnsatisfiedLinkError: java.lang.UnsatisfiedLinkError: com.comsol.nativejni.util.FlLicense.initWS0(Lcom/comsol/nativejni/CPointer;)V
```

Don't have the bandwidth to pursue this right now, but it looks to be some sort of missing library issue. E.g.
https://stackoverflow.com/questions/538886/java-lang-unsatisfiedlinkerror-in-linux

Best,
Jacob

**Comment by John-Hennig** [comment]
Closed this accidentally. Got the issue numbers wrong in commit messages.

**Comment by John-Hennig** [comment]
I have (finally) integrated this into master (after a rebase) and added you as a contributor. I also added more code to support stand-alone client operation. Which works... to a degree. Details in the documentation as of version 0.8.0, released today, as well as in issue #8. It still does not *fully* work out of the box, but that's as far as I got.

**Pull request closed without merging**
