### PR TITLE
Adding the availability to supply a custom model class

### PR DESCRIPTION
**Pull request by max3-2**
This helps a user to use his own model class which inherits model but adds custom methods for common tasks specific to each user.

I do see this the easiest way of allowing an expanded usability without having t much in the code. If there's another way or this is not a good idea, let me know.

### CODE REVIEW

**Comment by John-Hennig** [comment]
Seems a bit convoluted. Then the class definition of `Model` would depend on a class definition of `Model` or its child class.

I think you'd rather extend the `Model` class like so:
```python
import mph


class MyModel(mph.Model):

    def version(self):
        return str(self.java.getComsolVersion())


client = mph.Client()
model = client.load('tests/capacitor.mph')
mymodel = MyModel(model.java)
print(mymodel.version())
```

This isn't exactly like "casting". ([Python does not support "casting".](https://stackoverflow.com/questions/10030412)) But it works as long as the signature of the constructor doesn't change: `__init__(self, java)`. And even then one could still redefine `__init__` and call `super()`.

You could also [monkey-patch the instance](https://stackoverflow.com/questions/972) (`mymodel`) or, better, the `Model` class with custom methods if that's fewer lines of customization code.

**Comment by max3-2** [comment]
> hen the class definition of Model would depend on a class definition of Model or its child class.

How so? If not passed to `Client`, nothing is changed.

I intended to enable the user to build a e.g. `customModel.py` which could be simply

```python
import mph

class MyModel(mph.Model):
    def __init__(self):
        super().__init__()

    def customMethod(self):
       print('Do something')
```

and then it would be as easy as

```python
import mph
from customModel import MyModel

client = mph.Client(modelClass=MyModel)
model = client.load('tests/capacitor.mph')
model.customMethod()
```

No patching required. If I do not want to touch `Client`, I would have to wrap each load call with a *typecast*. I could tinker with the Model class itself, but not without accessing the installed package files, which I think is not good practice (except the *monkey patching* which I do not think is too elegant.

**Comment by John-Hennig** [comment]
In my earlier comment, I should have said: "…the class definition of `Client` would depend on…". Not `Model`. But I still find that a strange construct. I can't think of a Python library that does something like that.

What's the problem with the "typecast" on each load? It doesn't even add an extra line of code. Instead of
```python
model = client.load('tests/capacitor.mph')
```
you'd just do:
```python
model = MyModel(client.load('tests/capacitor.mph').java)
```

Otherwise the code is exactly the same, no patching, no tinkering. The only thing that's a bit ugly there is the `.java` at the end. But that we could get rid of more easily.

Explicit is better than implicit, as the Zen of Python says. What if a user has several custom classes? One for each physics problem they're solving. Then they'd have to reconfigure the client before each call to `load()`. The `Client` shouldn't keep state information like that, that's not really the responsibility of that particular class. It's better to make that explicit in the code.

**Comment by max3-2** [comment]
In the end, I dont like either approach.
I do see the implicitness with mine and the confusion for any other user. However I do see me going back into each code twice, first to fix the Model and then to fix the `.java`. But this, in the end, is my own stupidity. I will probably build a small wrapper around that with *my* custom model to circumvent locally. 

I will close this PR - if we need something like this its nothing too fancy to dig out again...

**Comment by John-Hennig** [comment]
I've just pushed a commit to make inheritance a tad easier: eb42e239bec1dfff19fb2475382c28c0c11199e7. Means the `.java` can be dropped when type-casting to a child class. Though the old way also still works.

**Pull request closed without merging**
