### PR TITLE
M32 model features

### PR DESCRIPTION
**Pull request by max3-2**
As discussed in #25 this will allow many new possibilities. Please let me know if you need any more changes

### CODE REVIEW

**Comment by John-Hennig** [comment]
Max, help me understand something... `apply_interpolation()` basically does the same as `property()`, right? As in, it also sets a property on a node, only that node is in a physics interface and not in one of the "standard" groups. Because then we should find a way to consolidate it all into one method.

**Comment by max3-2** [comment]
Yes It does - I kinda patched that one in since I realized this would be convenient during testing. But it is not a good approach on second thought. I had the idea that maybe we can add physics to the groups so it would be ´model.property(‘physics‘, ...)´ however that would be a third *level* which I did not like too much either. 

Another idea would be to allow levels like the above via some sort of smart typing, eg allowing ´-> to specify to go down into the tree?

**Comment by John-Hennig** [comment]
I think adding the names of physics interfaces as "dynamic" groups works. It's like: check `self._groups`, then check `self.physics()`, if it's not in either, raise error. This could even be extended to named mesh sequences etc. It's not perfect, because the dynamic groups might shadow some of the standard groups. But that's quite unlikely and also kind of on the user, really. This would be a name collision they can see coming, as they're the ones setting up the model. And if we wanted to make this fool-proof, we could even check that there is no collision and raise an error early.

Using `->` or something to denote hierarchy is another option, yes, but would require quite a bit more code as we'd have to parse the string. I think it would add quite some of complexity, and remove very little ambiguity.

**Comment by max3-2** [comment]
So to get this right: you suggest allowing group to be a subgroup and then mph checks if this is a group or a subgroup (either in groups we hard code or allowing the search in any of the groups)?

From a coding position, this might be easier. From a users standpoint I do see an advantage specifying the hierarchy. This makes it easier when going back to the code after a while.
Also this resolves the issue with 3rd levels as present with special features eg thin layers where the field data is specified under a sub-feature. We could traverse _node() iteratively I guess 

The use of -> is fairly pythonic (numpy does it too) but we could use something else too. I could make either solution or one of the two during the next few days let me know which one (or both for testing) you prefer

**Comment by John-Hennig** [comment]
See, if we introduce the hierarchy notation, then we shouldn't have groups at all, as they are just the top level in that hierarchy. Maybe that's the better way to go, I don't know. We'd just have `create(node, type)` and `property(node, name, value=None)`, where `node` would be a string like "functions->test interpolation". And then we can change properties on that node, and we could also have `toggle()` operate on general nodes, not just physics features.

But I have a hard time seeing how this API could fully replace the Java-like syntax, such as in this [example from the documentation](https://mph.readthedocs.io/en/v0.9.1/demonstrations.html#creating-models):

```python
import mph

client = mph.start()
pymodel = client.create('model')
model = pymodel.java

model.modelNode().create("comp1");
model.geom().create("geom1", 3);
model.geom("geom1").feature().create("blk1", "Block");
model.geom("geom1").feature("blk1").set("size", ["0.1", "0.2", "0.5"]);
model.geom("geom1").run("fin");
```

I don't want something that only "half-works". So either we restrict the scope to certain groups (and clearly document which ones) or we find a way that covers everything. Again, I'm not sure if the latter isn't a bit too complex. Note how the above example also creates a model component, and passes the number of dimensions when creating the geometry sequence. None of which is covered by the API as is. We need a clear goal here, but I'm not sure yet what that goal would be. Ultimately, once this works and we like how it works, it should be demonstrated in the docs and either supplement or replace the above example.

Right now, I'm more concerned with the testing strategy. When we test the type-casting, we should do that via MPh (by either calling `model.property()` or `tools._typecast_property()`) and only test JPype indirectly with all the different types that might be passed in. Whatever we do, the type-casting functionality will definitely be exposed to users, as that saves them the time to figure out how JPype works.

**Comment by max3-2** [comment]
Lets start with the easy part - typecasting ;)
This is not too well designed. The typecasting is intertwined with the java model object due to either the type getter or the setter. Running a full test would need a model with nodes that accept each data type, which is very complicated. And if the typecasting works itself, I think testing if COMSOL accepts the type at a certain position is not needed on this side. 
If we would externalize the calls that use `.java` to the `property()` method, typecasting could be  stand-alone and subsequently fairly easy to test. With the small drawback that the call on either get or set would look different - maybe we should do to different functions for each *direction* here. Again something I could work on around the coming days if this is a solution..

Groups: The main question is on if you want the user to never use java or to have some functionality and encourage the use of java use for more complex tasks. I do not think that hirarchy completely removes the need of java and I think the documentation at the referenced point is more to enable more features for an advanced user. In this thinking, I would limit the hirarchy to the groups we enable on root level and allow the dive into the features in this well controlled environment - especially when stuff like `model.create()` can take more arguments than expected by the simple call. This would generate a lot of functionality for common tasks and produce clean errors if the user steps onto terrain which is reserved for the use with the java-like API.
Again, no hurry here lets find the best solution - I will be happy to work on the implementation as soon as we have a clear goal.

**Pull request merged**
